### ISSUE TITLE
Replace Travis/GoCD with github actions

### ISSUE THREAD

**Issue by ctk3b** [counsyl/capone#14]
Example: https://github.com/myriad-opensource/samwell/blob/master/.github/workflows/pythonpackage.yml

**Comment by hrichards** [comment]
PRs in progress have their status checked by GitHub actions, but promotion to public PyPI still happens internally in a GoCD pipeline.  To truly remove all reliance on GoCD, we'll need to figure out how to do PyPI promotion in GHA.

**Comment by hrichards** [comment]
Done in #16.
